### ISSUE TITLE
Train Flux_mini CUDA out of memory.

### ISSUE THREAD

**Issue by kelisiya** [TencentARC/FluxKits#3]
When I train flux_mini KD use Flux_dev in 80G A100 , [rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 11.84 GiB. GPU

**Comment by daoyuan98** [comment]
How many GPUs did you use? and what is the batch size on each? One GPU may not be enough, training on 8 A100 with deepspeed stage 2 would allow a reasonable batch size.

**Comment by kelisiya** [comment]
> How many GPUs did you use? and what is the batch size on each? One GPU may not be enough, training on 8 A100 with deepspeed stage 2 would allow a reasonable batch size.

Would 1 or 2 80G A100s allow me to successfully run the training code, given my current batch size of 1? I also have 8*40G A100 ; which one would be more suitable?

**Comment by daoyuan98** [comment]
With 1024 resolution, our training was performed on 16 910B NPUs, each using a batch size of 1 and we use gradient accumulation=8 to enlarge the effective batch size.
