### ISSUE TITLE
how to initialize the student model's weights?

### ISSUE THREAD

**Issue by youngwanLEE** [TencentARC/FluxKits#4]
Hi, I'm impressed by your work. 

I have a question about the train_flux_distill.py.  

For training from scratch, without using flux-mini weights, I couldn't find where the `pick_up_weights` function is called for the student model initialization. 

I wonder how to set the initial weights for the student model.

Thanks in advance.

**Comment by daoyuan98** [comment]
Thank you for your attention.

The double blocks of the student are initialized with the [0, 1, 2, 10, 18]-th double block of the teacher, and single blocks are initialized with [3, 7, 11, 15, 19, 23, 27, 31, 35, 37]-th single block of the teacher. 

The `pick_up_weights` function should be called when loading the student model... We will fix the code soon.

**Comment by youngwanLEE** [comment]
@daoyuan98 thank you for your quick reply.

I have another question. 

Is it possible to train the flux-mini using using `train_flux_distill.py` with 1024px in an 8xA100(80GB) GPU machine? 

I wonder about the exact GPU environment when you trained the flux-mini model.

Thanks in advance.

**Comment by daoyuan98** [comment]
> Is it possible to train the flux-mini using using train_flux_distill.py with 1024px in an 8xA100(80GB) GPU machine?

Yes, I think that should be ok for you to train flux-mini under our setting. 

> I wonder about the exact GPU environment when you trained the flux-mini model.

Our training was mainly conducted on ASCEND 910B NPUs, each node has 16 NPUs. When setting batch-size=1 and 1024px on each NPU, (with deepspeed stage=2) each node takes about 60GB NPU memory. I think the memory cost should be similar on GPUs.

**Comment by youngwanLEE** [comment]
@daoyuan98 Thanks for your quick reply.

 I wonder why you set different indice to match between slim and target in double-stream transformer blocks, unlike the single-stream blocks.

> distill_slim_double: [0, 1, 2, 10, 18]
distill_target_double: [3, 7, 11, 15, 18]
distill_slim_single: [3, 7, 11, 15, 19, 23, 27, 31, 35, 37] 
distill_target_single: [3, 7, 11, 15, 19, 23, 27, 31, 35, 37]

**Comment by daoyuan98** [comment]
Because we empirically found some double blocks are especially important (i,e,m 0,1,2,10,18), removing them leads to corrupted generation results. While in single blocks, the blocks are not that important, so we use an interval of 4 to initialize the student models.

**Comment by youngwanLEE** [comment]
@daoyuan98 I also found that the initial blocks in double stream blocks are more important than others, but I'm curious about the intention that you set the different indices target against the slim_double,e.g., 0 <-> 3, 1 <-> 7, 2 <-> 11, etc.

**Comment by daoyuan98** [comment]
> @daoyuan98 I also found that the initial blocks in double stream blocks are more important than others, but I'm curious about the intention that you set the different indices target against the slim_double,e.g., 0 <-> 3, 1 <-> 7, 2 <-> 11, etc.

Our intuition is that the blocks used for initialization contain the most important information from the original model, but to recover the capability of the original model, we hope one single block can match the capability of ~4 blocks in the teacher model.
